### ISSUE TITLE
Issues on other repos

### ISSUE THREAD

**Issue by brumhard** [pulumiverse/awesome-pulumi#17]
Hi there,

first of all it's great to have the pulumiverse, ty for that.

I was just wondering why exactly the issues are disabled on some of the other repos.
For example I would like to contribute on the concourse repo since I'm working on [sth like that](https://github.com/brumhard/pulumi-concourse) as well and maybe we could join efforts.

Also the project's README says you should open an issue to join the discussion and that's currently not possible.

**Comment by ringods** [comment]
@brumhard that is an oversight from migrating this repo from my personal Github account to Pulumiverse. I'll activate the issues right away.

**Comment by brumhard** [comment]
Hi @ringods looks like issues are disabled again. At least I can't access my issue at https://github.com/pulumiverse/pulumi-concourse anymore

**Comment by ringods** [comment]
@brumhard this should solve it permanently. Sorry for the hickup!

https://github.com/pulumiverse/infra/commit/e7490c750fad6735051da406534587f7d3498f32

**Comment by brumhard** [comment]
Looks good again 👍🏻
